spring:
  # https://console.aiven.io/signup
  datasource:
    url: jdbc:mysql://mysql-{}.aivencloud.com:13118/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_{}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # DROP TABLE IF EXIST memo
  # # user_account와 엮여 있으므로 이걸 따로 실행해주시는게...
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

# 1-2
# JWT 설정값
# 1. JWT로 값을 변환 -> 기준이 될 비밀키
# 2. 만료일시 -> 몇분, 몇시간 뒤에 만료될지 Mill초 -> 초 * 1000
jwt:
  # jwt secret key generator -> 예) https://jwtsecrets.com/
  # openssl rand -hex 64
  secret: {}
  access-token-expiry: 900000 # 1000 * 60 (1초) * 15 => 15분